apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openruntimes-executor.fullname" . }}
  labels:
    {{- include "openruntimes-executor.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPR_EXECUTOR_SECRET: {{ .Values.secret.executorSecret | quote }}
  {{- if .Values.secret.dockerHub.username }}
  OPR_EXECUTOR_DOCKER_HUB_USERNAME: {{ .Values.secret.dockerHub.username | quote }}
  {{- end }}
  {{- if .Values.secret.dockerHub.password }}
  OPR_EXECUTOR_DOCKER_HUB_PASSWORD: {{ .Values.secret.dockerHub.password | quote }}
  {{- end }}
